cars_analytics:

  target: cars_dev
  
  outputs:
    cars_dev:
      type: clickhouse
      schema: cars_dev
      host: 35.189.109.115
      password: ''
    
    cars_test:
      type: clickhouse
      schema: cars_test
      host: 35.189.109.115
      password: ''

    cars_production:
      type: clickhouse
      schema: cars_production
      host: 35.189.109.115
      password: ''
